services:
  next-dev:
    build:
      context: .
    image: next-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - node_modules/
        - action: sync
          path: ./components
          target: /app/components
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pov_local_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5432:5432"

volumes:
  db-data:
