import type { Metadata } from "next";
import NavBar from "../components/nav/NavBar";

// These styles apply to every route in the application
import "./globals.css";
import { Cutive_Mono } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cutiveMono = Cutive_Mono({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cutiveMono.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
